version: "3.4"

services:
  web:
    build: .
    restart: unless-stopped
    volumes:
      - .:/code
      - media-volume:/code/media
    networks:
      - sennearchiv
    environment:
      SECRET_KEY: "i-should-change-this"
      DEBUG: "False"

  proxy:
    image: nginx:1.15-alpine
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:sennearchiv.de,www.sennearchiv.de"
      - "traefik.frontend.redirect.regex=^https?://www.sennearchiv.de/(.*)"
      - "traefik.frontend.redirect.replacement=https://sennearchiv.de/$${1}"
      - "traefik.port=80"
      - "traefik.docker.network=web"
    networks:
      - web
      - sennearchiv
    volumes:
      - ./proxy/conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./proxy/conf/domain.conf:/etc/nginx/domain.conf:ro
      - ./static/:/usr/share/nginx/html/static/
      - media-volume:/usr/share/nginx/html/media/
    depends_on:
      - web

volumes:
  media-volume:

networks:
  web:
    external: true
  sennearchiv:
    driver: bridge
