version: "3.4"

services:
  web:
    build: .
    restart: unless-stopped
    volumes:
      - .:/code
    networks:
      - sennearchiv
    environment:
      SECRET_KEY: "i-should-change-this"
      DEBUG: "False"

  proxy:
    image: nginx:1.15-alpine
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:sennearchiv.de"
      - "traefik.port=80"
      - "traefik.docker.network=web"
    networks:
      - web
      - sennearchiv
    volumes:
      - ./proxy/conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./proxy/conf/domain.conf:/etc/nginx/domain.conf:ro
      - ./static/:/usr/share/nginx/html/static/
      - ./media/:/usr/share/nginx/html/media/
    depends_on:
      - web

networks:
  web:
    external: true
  sennearchiv:
    driver: bridge
