version: "3.4"

services:
  web:
    build: .
    restart: unless-stopped
    volumes:
      - .:/code
    environment:
      SECRET_KEY: "i-should-change-this"
      DEBUG: "False"

  proxy:
    image: nginx:1.15-alpine
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./proxy/conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./proxy/conf/domain.conf:/etc/nginx/domain.conf:ro
      - ./static/:/usr/share/nginx/html/static/
      - ./media/:/usr/share/nginx/html/media/
    depends_on:
      - web